version: "3.8"
services:
  parquimetro-app:
    image: felipebatista765/parquimetro:v0.0.4
    container_name: "docker-app"
    ports:
      - 8080:8080
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb/parquimetro-spring
  mongodb:
    image: mongo:8.0.0
    container_name: "mongodb"
    ports:
      - 27070:27017